BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE train_routes (
       id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
       name VARCHAR2(255 CHAR) NOT NULL UNIQUE,
       description CLOB,
       PRIMARY KEY (id)
   )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE train_route_definitions (
       id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
       route_id NUMBER(19,0) NOT NULL,
       station_id NUMBER(19,0) NOT NULL,
       stop_order NUMBER(10,0) NOT NULL,
       distance_from_prev_km FLOAT(53),
       standard_travel_time_mins NUMBER(10,0),
       PRIMARY KEY (id),
       CONSTRAINT fk_route_def_route FOREIGN KEY (route_id) REFERENCES train_routes(id),
       CONSTRAINT fk_route_def_station FOREIGN KEY (station_id) REFERENCES stations(id)
   )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
         RAISE;
      END IF;
END;
/
